### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [LEDSupplyCo/prj-rev-bwfs-dasmoto#5]
Fantastic job on this project! I really liked how you chose to set the font-family once, and how you decided to use divs to organize your HTML. In terms of improvement, I recommend using only a relative path to link your CSS. 

If you’re in the mood for a challenge...I would look into adding more items under each section and finding a nice way to lay them out. Here's a link to get you started - https://www.w3schools.com/css/css_rwd_grid.asp. Keep up the awesome work! ^_^

**Comment by LEDSupplyCo** [comment]
Thank you for the Review, Jen!
